In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("vins_vinatis_flat_complet.csv")
df.head()

,advanced_stock_management,contenance,indice_comportementale,id,affichage_special_pack,disponible,image,accroche,franco,weight,...,comment_note_sur_20,other_products_0,other_products_1,other_products_2,other_products_3,other_products_4,other_products_5,other_products_6,other_products_7,other_products_8
0,0,0.75,37,72739,False,15213,94492-fine_default/colombard-sauvignon-2024-ho...,"Savoureux <a class=""maillage"" href =""/vin-d-ho...",False,1.18,...,NaN,"{'id_image': 94492, 'vintage': 2024, 'id': 727...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0.75,37,73560,False,4791,95769-fine_default/le-bal-des-papillons-2024-h...,Plongez dans un univers de légèreté et d’éléga...,True,1.19,...,NaN,"{'id_image': 95769, 'vintage': 2024, 'id': 735...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0.75,37,57419,False,4248,93877-fine_default/villa-des-anges-reserve-202...,Un cuvée emblématique de la sélection qui ravi...,False,1.26,...,NaN,"{'id_image': 93877, 'vintage': 2021, 'id': 574...","{'id_image': 94693, 'vintage': 2021, 'id': 635...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0.75,37,63000,False,25798,80831-fine_default/lupo-meraviglia-tre-di-tre-...,Une étoile montante des Pouilles vinifiée selo...,True,1.17,...,NaN,"{'id_image': 80831, 'vintage': 2022, 'id': 630...","{'id_image': 86870, 'vintage': 2022, 'id': 666...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0.75,37,75247,False,11041,98180-fine_default/n3-colombard-sauvignon-blan...,La référence incontestable des Côtes de <a cla...,False,1.15,...,NaN,"{'id_image': 98180, 'vintage': 2024, 'id': 752...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
colonnes = [
    'id',
    'name',
    'description_short',
    'accroche',
    'image_url',
    'manufacturer_name',
    'contenance',
    'features_abv',
    'features_country',
    'features_region',
    'features_appellation',
    'features_full_grape_variety',
    'features_vintage',
    'features_food_and_wine_matching',
    'features_taste',
    'features_character',
    'features_colour',
    'features_service_temperature',
    'features_type',
    'features_bio',
    'prices_price']
df_select=df[colonnes]
#Colonnes à sélectionner et leurs nouveaux noms
colonnes_fr = {
    'id':'id',
    'name': 'nom',
    'description_short': 'desc',
    'accroche': 'accroche',
    'image_url': 'visuel',
    'manufacturer_name': 'producteur',
    'contenance': 'contenance',
    'features_abv': 'deg_alcool',
    'features_country': 'pays',
    'features_region': 'region',
    'features_appellation': 'appellation',
    'features_full_grape_variety': 'cepages',
    'features_vintage': 'millesime',
    'features_food_and_wine_matching': 'accords',
    'features_taste': 'gout',
    'features_character': 'caractere',
    'features_colour': 'couleur',
    'features_service_temperature': 'temp_serv',
    'features_type': 'type_produit',
    'features_bio': 'bio',
    'prices_price':'prix'}

df_select=df_select.rename(colonnes_fr,axis=1)

df_select.head()

,id,nom,desc,accroche,visuel,producteur,contenance,deg_alcool,pays,region,...,cepages,millesime,accords,gout,caractere,couleur,temp_serv,type_produit,bio,prix
0,72739,Colombard-Sauvignon 2024 - Horgelus,<p>L'harmonieux mariage du colombard et du sau...,"Savoureux <a class=""maillage"" href =""/vin-d-ho...",https://www.vinatis.com/72739-detail_default/c...,Horgelus,0.75,11.5,France,Sud-Ouest,...,NaN,2024,"['Apéritif', 'Entrée', 'Foie gras', 'Fromage',...",Bouche franchement ronde et fraîche. Finale nette,Blanc Sec souple et fruité,Blanc,10°C,Vin,NaN,6.6
1,73560,Le Bal des Papillons 2024 - Horgelus,<p>Élaborée avec soin dans le respect des trad...,Plongez dans un univers de légèreté et d’éléga...,https://www.vinatis.com/73560-detail_default/l...,Horgelus,0.75,11.0,France,Sud-Ouest,...,NaN,2024,"['Apéritif', 'Entrée', 'Foie gras', 'Fromage',...",Une harmonie parfaite entre vivacité et douceu...,"Blanc Demi-sec, moelleux et liquoreux",Blanc,8-10°C,Vin,NaN,8.6
2,57419,Villa des Anges - Réserve 2021 - Jeff Carrel,"<p>La gamme Villa des Anges fait <a class=""mai...",Un cuvée emblématique de la sélection qui ravi...,https://www.vinatis.com/57419-detail_default/v...,Jeff Carrel,0.75,14.0,France,NaN,...,NaN,2021,"['Charcuterie', 'Viande rouge', 'Viande blanch...","Bouche élancée, tendue par une fine acidité in...",Rouge Charnu et fruité,Rouge,14-16°C,Vin,NaN,9.5
3,63000,Lupo Meraviglia Tre di Tre 2022 - Botter,"<p>Historiquement, la vinification dans les Po...",Une étoile montante des Pouilles vinifiée selo...,https://www.vinatis.com/63000-detail_default/l...,Botter,0.75,14.5,Italie,Pouilles,...,NaN,2022,"['Apéritif', 'Entrée', 'Charcuterie', 'Viande ...",Bouche délicate et persistante sur des saveurs...,Rouge Charnu et fruité,Rouge,16-18°C,Vin,NaN,10.9
4,75247,N°3 - Colombard-Sauvignon Blanc 2024 - UBY,"<p>Léger et fruité ! Ce vin <a class=""maillage...",La référence incontestable des Côtes de <a cla...,https://www.vinatis.com/75247-detail_default/n...,UBY,0.75,11.0,France,Sud-Ouest,...,NaN,2024,"['Apéritif', 'Poisson', 'Coquillage & Crustacé...","L’attaque fraîche et ronde, s'ouvre sur un pal...",NaN,Blanc,10-12°C,Vin,NaN,6.5

In [5]:
df_select=df_select.set_index('id')

df_select.describe()

        contenance   deg_alcool          prix
count  5067.000000  4840.000000   5067.000000
mean      0.941944    13.315950     75.955613
std       0.732264     1.094836    768.043725
min       0.250000     1.200000      4.900000
25%       0.750000    13.000000     14.500000
50%       0.750000    13.500000     25.100000
75%       0.750000    14.000000     50.000000
max       9.000000    18.000000  43000.000000

In [6]:
df_select.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5067 entries, 72739 to 70578
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nom           5067 non-null   object
 1   desc          5062 non-null   object
 2   accroche      5059 non-null   object
 3   visuel        5050 non-null   object
 4   producteur    4888 non-null   object
 5   contenance    5067 non-null   float64
 6   deg_alcool    4840 non-null   float64
 7   pays          5026 non-null   object
 8   region        4812 non-null   object
 9   appellation   4758 non-null   object
 10  cepages       2534 non-null   object
 11  millesime     4701 non-null   object
 12  accords       4867 non-null   object
 13  gout          4803 non-null   object
 14  caractere     4631 non-null   object
 15  couleur       4938 non-null   object
 16  temp_serv     4769 non-null   object
 17  type_produit  5067 non-null   object
 18  bio           1315 non-null   object
 19  prix          5067 non-null   float64
dtypes: float64(3), object(17)
memory usage: 831.3+ KB

In [19]:
print(df_select.isna().sum().sort_values(ascending=False))

bio             3752
cepages         2533
caractere        436
millesime        366
appellation      309
temp_serv        298
gout             264
region           255
deg_alcool       227
accords          200
producteur       179
couleur          129
pays              41
visuel            17
accroche           8
desc               5
type_produit       0
nom                0
contenance         0
prix               0
dtype: int64

In [18]:
for col in ['pays', 'millesime', 'couleur="nan"']:
    print(f"\n--- {col} ---")
    print(df_select[col].unique())

--- pays ---
['France' 'Italie' 'Espagne' 'Chili' 'Nouvelle-Zélande' 'Argentine'
 'Etats-Unis' 'Allemagne' 'Afrique du Sud' 'Moldavie' nan 'Portugal'
 'Pérou' 'Australie' 'Autriche' 'Turquie' 'Croatie' 'Uruguay' 'Slovénie'
 'Maroc' 'Chine' 'Roumanie' 'Hongrie' 'Suisse' 'Géorgie' 'Canada' 'Grèce'
 'Liban' 'Bulgarie' 'Angleterre' 'Mexique' 'Arménie' 'Plateau du Golan']

--- millesime ---
['2024' '2021' '2022' '2023' nan '2020' '2019' '2017' '2015' '2016' '2018'
 'non millésimé' '2012' '2010' '2014' '1998' '2013' '1980' '1959' '2009'
 '2008' '1974' '2001' '1989' '1995' '1969' '2004' '2011' '2003' '2005'
 '1979' '2000' '2007']

--- couleur="nan" ---

KeyError: 'couleur="nan"'